apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: roboshop
  labels:
    project: roboshop
    tier: database
    component: mongodb
    environment: dev
spec:
  selector:
      project: roboshop
      tier: database
      component: mongodb
      environment: dev

  ports:
  - protocol: TCP
    port: 27017
    targetPort: 27017
