apiVersion: v1
kind: ConfigMap
metadata:
  name: rabbitmq-configmap
  namespace: roboshop
  labels:
    project: roboshop
    tier: database
    component: rabbitmq
    environment: dev

data:
  RABBITMQ_DEFAULT_USER: "roboshop"
  RABBITMQ_DEFAULT_PASS: "roboshop123"
